Fix datadir in make.py "install" action
The variable name for the installation of the data in the make.py
install action was incorrect. This caused make.py to fail with:

  Traceback (most recent call last):
    File "./make.py", line 534, in <module>
      main(extra_options=[j])
    File "/sw/build.build/boswars-2.8-1/boswars-2.8-src/fabricate.py", line 1046, in main
      this_status = f(**action[1])
    File "./make.py", line 524, in install
      install_data(installdatadir)
  NameError: global name 'installdatadir' is not defined

Fix #69 "datadir not accepted during install and other make.py
install errors"