Raise a RuntimeError instead of a string.
Trying to raise a string fails :
 TypeError: exceptions must be old-style classes or derived from
 BaseException, not str